openapi: 3.0.3
info:
  title: RAG Backend - Password Reset API
  description: Password reset endpoints for user self-service account recovery
  version: 1.0.0

paths:
  /api/v1/auth/forgot-password:
    post:
      summary: Request password reset
      description: |
        Send a password reset email to the user. Always returns success to prevent
        email enumeration attacks, even if the email is not registered.
      operationId: requestPasswordReset
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
      responses:
        '200':
          description: Reset email sent (or no-op if email not found)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForgotPasswordResponse'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateLimitError'

  /api/v1/auth/reset-password:
    post:
      summary: Reset password with token
      description: |
        Reset the user password using the token from the reset email.
        Token must be valid and not expired (1 hour validity).
      operationId: resetPassword
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        '200':
          description: Password reset successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResetPasswordResponse'
        '400':
          description: Invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'

  /api/v1/auth/verify-reset-token:
    get:
      summary: Verify reset token validity
      description: |
        Check if a password reset token is valid before showing the reset form.
        Does not consume the token.
      operationId: verifyResetToken
      tags:
        - Authentication
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
          description: The password reset token
      responses:
        '200':
          description: Token is valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenValidResponse'
        '400':
          description: Token is invalid or expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ForgotPasswordRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
          description: User email address
          example: user@example.com

    ForgotPasswordResponse:
      type: object
      properties:
        message:
          type: string
          example: If an account with that email exists, a reset link has been sent.
        success:
          type: boolean
          example: true

    ResetPasswordRequest:
      type: object
      required:
        - token
        - new_password
      properties:
        token:
          type: string
          description: Password reset token from email
          example: abc123def456...
        new_password:
          type: string
          format: password
          minLength: 8
          description: New password (minimum 8 characters)
          example: NewSecurePassword123!

    ResetPasswordResponse:
      type: object
      properties:
        message:
          type: string
          example: Password has been reset successfully. Please log in.
        success:
          type: boolean
          example: true

    TokenValidResponse:
      type: object
      properties:
        valid:
          type: boolean
          example: true
        expires_in_seconds:
          type: integer
          description: Seconds until token expires
          example: 3540

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          example: Invalid or expired reset token
        error_code:
          type: string
          example: INVALID_TOKEN

    ValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  type: string
              msg:
                type: string
              type:
                type: string

    RateLimitError:
      type: object
      properties:
        detail:
          type: string
          example: Rate limit exceeded. Please try again later.
        retry_after:
          type: integer
          example: 60
        error_code:
          type: string
          example: RATE_LIMIT_EXCEEDED
